from turtle import Screen, Turtle

PIXEL_SIZE = 15
CURSOR_SIZE = 15

COLORS = {
    'B': 'blue',
    'K': 'black',
    'O': 'orange',
    'R': 'red',
    'T': 'brown',
    'W': 'white',
    'G': 'grey',
}

PIXELS = [
    "WWWWWWWWWWWWWWWWWWWWKKKWWWWKKKWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWKWWWKWWKWWWKWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWKWWWWWKKWWWWWKWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWKWWWWWKKWWWWWKWWKKWWWW",
    "WWWWWWWWWWWWWWWWWWKWWWWWKKWWWWWKWKWWKWWW",
    "WWWWWWWWWWWWWWWWWWKWWWWWKKWWWWWKKWWWWKWW",
    "WWWWWWWWWWWWWWWWWWKWWWWWKKWWWWWKKWWWWKWW",
    "WWWWWWWWWWWWWWWWWWKWWWWWKKWWWWWKKWWWWKWW",
    "WWWWWWWWWWWWWWWWWWKWWWWWKKWWWWWKKWWWWKWW",
    "WWWWWWWWWWWWWWWWWWKWWWWWKKWWWWWKKWWWWKWW",
    "WWWWWWWWWWKKKKWWWWKWWWWWKKWWWWWKKWWWWKWW",
    "WWWWWWWWWKWWWWKWWWKWWWWWKKWWWWWKKWWWWKWW",
    "WWWWWWWWWKWWWWWKWWKWWWWWKKWWWWWKKWWWWKWW",
    "WWWWWWWWWKWWWWWWKWKWWWWWKKWWWWWKKWWWWKWW",
    "WWWWWWWWWWKWWWWWWKKWWWWWWWWWWWWWWWWWWKWW",
    "WWWWWWWWWWKWWWWWWKKWWWWKKWWWKKWWWWWWWKWW",
    "WWWWWWWWWWKWWWWWWKKWWWWKKWWWKKWWWWWWWKWW",
    "WWWWWWWWWWWKWWWWWWKWWWKWWWWWWWKWWWWWWKWW",
    "WWWWWWWWWWWWKWWWWWKWWWWWKWWWKWWWWWWWWKWW",
    "WWWWWWWWWWWWKWWWWWWWWWWWWWWWWWWWWWWWWKWW",
    "WWWWWWWWWWWWWKWWWWWWWWWWWKKKKWWWWWWWWKWW",
    "WWWWWWWWWWWWWKWWWWWWWWWWKRRRRKWWWWWWWKWW",
    "WWWWWWWWWWWWWWKWWWWWWWWKRRRRRRKWWWWWWKWW",
    "WWWWWWWWWWWWWWKWWWWWWWWKRRRRRRKWWWWWWKWW",
    "WWWWWWWWWWWWWWKWWWWWWWWWKRRRRKWWWWWWWKWW",
    "WWWWWWWWWWWWWWKWWWWWWWWWWKKKKWWWWWWWWKWW",
    "WWWWWWWWWWWWWWWKWWWWWWWGWWWWWWGWWWWWWKWW",
    "WWWWWWWWWWWWWWWKWWWWWWWWGKKKKGWWWWWWKWWW",
    "WWWWWWWWWWWWWWWWKWWWWWWWWGKKGWWWWWWWKWWW",
    "WWWWWWWWWWWWWWWWKWWWWWWWWWWWWWWWWWWWKWWW",
    "WWWWWWWWWWWWWWWWKWWWWWWWWWWWWWWWWWWKWWWW",
    "WWWWWWWWWWWWWWKKKKKKKKKKKKKKKKKKKKKKKKKW",
    "WWWWWWWWWWWWWKRRRRRRRRRRRRRRRRRRRRRRRRRK",
    "WWWWWWWWWWWWWKRRRRRRRRRRRRRRRRRRRRRRRRRG",
    "WWWWWWWWWWWWWWKKKKKKKKKKKKKKKKKKKKKKKKGW",

]

WIDTH, HEIGHT = len(PIXELS[0]), len(PIXELS)

screen = Screen()
screen.setup((WIDTH ) * PIXEL_SIZE, (HEIGHT ) * PIXEL_SIZE)
screen.tracer(True)


turtle = Turtle()
turtle.hideturtle()
turtle.speed(300)
turtle.shape('square')
turtle.shapesize(PIXEL_SIZE / CURSOR_SIZE)
turtle.penup()

x0 = -WIDTH/2 * PIXEL_SIZE
y0 = HEIGHT/2 * PIXEL_SIZE

for i, row in enumerate(PIXELS):
    turtle.setposition(x0, y0 - i * PIXEL_SIZE)

    for pixel in row:
        turtle.color(COLORS[pixel])
        turtle.stamp()
        turtle.forward(PIXEL_SIZE)

screen.tracer(True)
screen.exitonclick()





